export const FETCH_TRENDING_TAGS = 'FETCH_TRENDING_TAGS';
export const FETCHING_RESULT = 'FETCHING_RESULT';
export const FETCH_RESULT = 'FETCH_RESULT';
export const UPDATE_STREAM_DATA = 'UPDATE_STREAM_DATA';
export const ADD_TAG = 'ADD_QUERY_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const SET_CHART_CONTROL = 'SET_CHART_CONTROL';
export const SWITCH_STREAM_MODE = 'SWITCH_STREAM_MODE';

export const SHOW_MSG_BOX = 'SHOW_MSG_BOX';
export const DISMISS_MSG_BOX = 'DISMISS_MSG_BOX';
