export const FETCH_TRENDING_TAGS = 'FETCH_TRENDING_TAGS';
export const FETCH_RESULT = 'FETCH_RESULT';
export const ADD_TAG = 'ADD_QUERY_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const SET_CHART_CONTROL = 'SET_CHART_CONTROL';
